server:
  servlet.context-path: /yueer
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/yueer?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: yueer
    password: sraxzscn170614
    tomcat:
      init-s-q-l: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: update
      database: MYSQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jmx:
    default-domain: yueer


  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


redis:
  database: 1
  host: 127.0.0.1
  port: 6379
  password: h0Q8Tj02Jp
  timeout: 0

#阿里云oos存储
oos:
  accessKeyId: LTAIXjdMD9qIc9Wl
  accessKeySecret: wb5Dhb2t9OPYqBK5LQrMkfv4T61acF
  endpoint: oss-cn-beijing.aliyuncs.com
  bucketName: yueer

logging:
  file: /opt/javalog/yueer/pro.log

