server:
  servlet.context-path: /chengxi
  port: 8080

#spring:
#  datasource:
#    url: jdbc:mysql://www.localhost.com/chengxi?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
#    username: chengxi
#    password: chenGxi125629
#    tomcat:
#      init-s-q-l: SET NAMES 'utf8mb4'
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:mysql://www.localhost.com:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123
    tomcat:
      init-s-q-l: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jmx:
    default-domain: chengxi

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

#redis:
#  database: 1
#  host: www.localhost.com
#  port: 6379
#  password: h08ipfsTj0Jp
#  timeout: 0
#
##阿里云oos存储
#oos:
#  accessKeyId: XXX
#  accessKeySecret: XXX
#  endpoint: oss-cn-beijing.aliyuncs.com
#  bucketName: chengxi

logging:
  file: /opt/javalog/chengxi/pro.log

