server:
  port: 80
#  servlet.context-path: /chengxi


spring:
  datasource:
    #url: jdbc:mysql://www.localhost.com:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
    url: jdbc:mysql://localhost:3306/meiye?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123
    tomcat:
      init-s-q-l: SET NAMES 'utf8mb4'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: update
      database: MYSQL
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

  jmx:
    default-domain: chengxi

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

redis:
  database: 1
  host: localhost
  port: 6379
  password: gezj123
  timeout: 0

#阿里云oos存储
#oos:
#  accessKeyId: XXX
#  accessKeySecret: XXX
#  endpoint: oss-cn-beijing.aliyuncs.com
#  bucketName: chengxi

#logging:
#  file: pro.log
logging:
  file:
    path: ./
    name: pro.log
